#!/bin/sh
while read file
do

  fullpath="$(pwd)/$file"
  case "$1" in
  "w")
    cp "$file" ~/.config/wall &&
    pkill swaybg;
    swaybg -i ~/.config/wall &
    notify-send "Wallpaper changed" -i "$PWD/$file";;
  
  "c")
    cp "$file" ~/.config/wall &&
    pkill swaybg;
    swaybg -i ~/.config/wall -m center &
    notify-send "Wallpaper changed" -i "$PWD/$file";;
  
  "s")
    cp "$file" ~/.config/wall &&
    pkill swaybg;
    swaybg -i ~/.config/wall -m stretch &
    notify-send "Wallpaper changed" -i "$PWD/$file";;

  "f")
    cp "$file" ~/.config/wall &&
    pkill swaybg;
    swaybg -i ~/.config/wall -m fit &
    notify-send "Wallpaper changed" -i "$PWD/$file";;

  "t")
    cp "$file" ~/.config/wall &&
    pkill swaybg;
    swaybg -i ~/.config/wall -m tile &
    notify-send "Wallpaper changed" -i "$PWD/$file";;

  "C-n")
    echo -n "$file" | xclip -selection clipboard &&
    notify-send.py "Image copied to clipboard" "$PWD/$file" --replaces-process "copy_wallpaper" --hint string:image-path:file://$PWD/$file;;

  "C-c")
    convert "$file" /tmp/tmp_sxiv_img.png &&
    xclip -selection clipboard -target image/png /tmp/tmp_sxiv_img.png &&
    notify-send.py "Image copied to clipboard" "$PWD/$file" --replaces-process "copy_wallpaper" --hint string:image-path:file://$PWD/$file;;


  "C-d")
    trash-put "$file" ;;
  
  esac
done
