#!/usr/bin/env sh

# Description: Open images in current directory in sxiv
#
# Shell: POSIX compliant
# Author: Arun Prakash Jana

# nsxiv -b -a -t -q $(ls -1 | sort -z) >/dev/null 2>&1 &
# $(find -L $(pwd) -maxdepth 1 -type f -print0 2>/dev/null | sort -z) | xargs -0 nsxiv -b -a -t -q "${count:--t}" --
find -L "$(pwd)" -maxdepth 3 -type f -print0 2>/dev/null | sort -z | xargs -0 nsxiv -b -a -t -q --
